Klipper-Adaptive-Meshing-Purging:
  type: git-repo
  url: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h

klipper-led_effect:
  type: git-repo
  url: https://github.com/julianschill/klipper-led_effect.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h

jschuh-klipper-macros:
  type: git-repo
  url: https://github.com/jschuh/klipper-macros.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h

klicky-probe:
  type: git-repo
  url: https://github.com/jlas1/Klicky-Probe.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h
