Klipper-Adaptive-Meshing-Purging:
  type: git-repo
  url: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h

klipper-led_effect:
  type: git-repo
  url: https://github.com/julianschill/klipper-led_effect.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h

jschuh-klipper-macros:
  type: git-repo
  url: https://github.com/jschuh/klipper-macros.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h

mainsail-config:
  type: git-repo
  url: https://github.com/mainsail-crew/mainsail-config.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h

sonar:
  type: git-repo
  url: https://github.com/mainsail-crew/sonar.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h

obico:
  type: git-repo
  url: https://github.com/TheSpaghettiDetective/moonraker-obico.git
  exact: true
  stripComponents: 0
  refreshPeriod: 24h
